#@formatter:off
name: flutter_tasks_7_3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  connectivity_plus: ^2.3.8
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_jailbreak_detection: ^1.10.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^4.2.1
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  intl_utils: ^2.8.7
  json_annotation: ^4.8.1
  loader_overlay: ^4.0.0
  logger: ^2.1.0
  mockito: ^5.4.4
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1
  retry: ^3.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  test: ^1.24.9

flutter:
  uses-material-design: true
  

    # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/launcher_icons/
    #   - images/a_dot_ham.jpeg


    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages




flutter_launcher_icons:
  image_path: "assets/launcher_icons/ic_launcher.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/launcher_icons/ic_launcher.png"
  windows:
    generate: true
    image_path: "assets/launcher_icons/ic_launcher.png"
  macos:
    generate: true
    image_path: "assets/launcher_icons/ic_launcher.png"



flutter_intl:
  enabled: true
  arb_dir: lib/app/localization/l10n
  output_dir: lib/app/localization/generated
  
#generated with mason